version: "3.1"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-kahoot}
    volumes:
      - kahoot:/var/lib/postgresql

  backend:
    image: golang-api
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
    build:
      context: ./backend/
    depends_on:
      - db

volumes:
  kahoot:
    external: false
